services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    hostname: tempo.localhost
    restart: unless-stopped
    command: ["-target=all", "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/resources/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "${TEMPO_OTLP_GRPC_PORT:-4317}:4317" # otlp grpc
      - "${TEMPO_OTLP_HTTP_PORT:-4318}:4318" # otlp http
    depends_on:
      - redpanda
    networks:
      - docker_compose_samples

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    hostname: redpanda.localhost
    restart: unless-stopped
    ports:
      - "9092:9092" # Kafka API for clients
    command: >
      redpanda start --overprovisioned
      --mode=dev-container
      --kafka-addr=PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    networks:
      - docker_compose_samples

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    hostname: redpanda-console.localhost
    restart: unless-stopped
    environment:
      - CONFIG_FILEPATH=/etc/redpanda/redpanda-console-config.yaml
    volumes:
      - ./docker/resources/redpanda/redpanda-console.yaml:/etc/redpanda/redpanda-console-config.yaml
    # ports:
    #   - "8080:8080"
    depends_on:
      - redpanda
    networks:
      - docker_compose_samples
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redpanda-console.rule=Host(`redpanda-console.localhost`)"
      - "traefik.http.routers.redpanda-console.entrypoints=web"
      - "traefik.http.services.redpanda-console.loadbalancer.server.port=8080"

volumes:
  tempo_data:

networks:
  docker_compose_samples:
    external: true
