services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localhost
    restart: always
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./docker/volumes:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_compose_samples

networks:
  docker_compose_samples:
    external: true
