version: '3.7'

services:
  # postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
    volumes:
      - ./docker/volumes/postgresql:/var/lib/postgresql/data
      - ./docker/resources/postgresql:/docker-entrypoint-initdb.d
    networks:
      - docker_compose_samples

  # adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    hostname: adminer.localhost
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: ng9
    # ports:
    #   - "8080:8080"
    depends_on:
      - postgres
    networks:
      - docker_compose_samples
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.routers.adminer.entrypoints=web"

networks:
  docker_compose_samples:
    external: true
