receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  # otlp/jaeger:
  #   endpoint: http://jaeger:4317
  #   tls:
  #     insecure: true
  # zipkin:
  #   endpoint: "http://zipkin:9411/api/v2/spans"
  #   format: proto

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, otlp/jaeger, zipkin]
  telemetry:
    logs:
      level: "info"
      encoding: json
      # processors:
      #   - batch:
      #       exporter:
      #         otlp:
      #           protocol: http/protobuf
      #           endpoint: http://loki:3100/otlp/v1/logs
