receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "*"
          allowed_headers:
            - "*"

processors:
  # メモリ制限
  memory_limiter:
    limit_mib: 200
    spike_limit_mib: 50
    check_interval: 5s

  # バッチ処理でパフォーマンス最適化
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

connectors:
  spanmetrics:
    dimensions:
      - name: service.instance.id
        default: unknown
    histogram:
      exponential:
    metrics_flush_interval: 10s
    metrics_expiration: 5m
    # mimirはDELTA temporalityをサポートしていない
    aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE

exporters:
  file/traces:
    path: /data/traces.jsonl
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 10
  file/logs:
    path: /data/logs.jsonl
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 10
  file/metrics:
    path: /data/metrics.jsonl
    rotation:
      max_megabytes: 10
      max_days: 7
      max_backups: 10

  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  otlphttp/mimir:
    endpoint: http://mimir-lb:9009/otlp

  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: normal

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug, file/traces, otlp/tempo, otlp/jaeger, zipkin ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug, file/logs, otlphttp/loki ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ debug, file/metrics, otlphttp/mimir, prometheus ]
  telemetry:
    logs:
      level: "info"
      encoding: json
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://loki:3100/otlp/v1/logs
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
