global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'otel-collector:8889' ]
      - targets: [ 'otel-collector:8888' ]

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: mimir
    static_configs:
      - targets: [ "mimir-1:8080" ]
        labels:
          pod: "mimir-1"
      - targets: [ "mimir-2:8080" ]
        labels:
          pod: "mimir-2"
      - targets: [ "mimir-3:8080" ]
        labels:
          pod: "mimir-3"
