version: "3.8"

services:
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    container_name: k6-tracing
    environment:
      - ENDPOINT=otel-collector:4317
    restart: always
    depends_on:
      - otel-collector
    networks:
      - docker_compose_samples

  otel-collector:
    image: otel/opentelemetry-collector:0.61.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./docker/resources/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
    networks:
      - docker_compose_samples

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    hostname: tempo.localhost
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/resources/tempo/tempo.yaml:/etc/tempo.yaml
      - ./docker/volumes/tempo/tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    networks:
      - docker_compose_samples

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus.localhost
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/resources/prometheus/prometheus.yaml:/etc/prometheus.yaml
    # ports:
    #   - "9090:9090"
    networks:
      - docker_compose_samples
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"

  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    hostname: grafana.localhost
    volumes:
      - ./docker/resources/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    # ports:
    #   - "3000:3000"
    networks:
      - docker_compose_samples
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"

networks:
  docker_compose_samples:
    external: true
