services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus.localhost
    restart: unless-stopped
    # ports:
    #   - '9090:9090'
    volumes:
      - ./docker/resources/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - docker_compose_samples
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --web.external-url=http://prometheus.localhost/
      - --enable-feature=exemplar-storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager.localhost
    restart: always
    # ports:
    #   - '9093:9093'
    volumes:
      - ./docker/resources/alertmanager:/etc/alertmanager
    networks:
      - docker_compose_samples
    command: "--config.file=/etc/alertmanager/alertmanager.yml --web.external-url=http://alertmanager.localhost/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.localhost`)"
      - "traefik.http.routers.alertmanager.entrypoints=web"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter.localhost
    restart: always
    # ports:
    #   - 9100:9100
    networks:
      - docker_compose_samples
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-exporter.rule=Host(`node-exporter.localhost`)"
      - "traefik.http.routers.node-exporter.entrypoints=web"

volumes:
  prometheus_data:

networks:
  docker_compose_samples:
    external: true
