services:
  # postgres
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./docker/volumes/postgresql:/var/lib/postgresql/data
    networks:
      - docker_compose_samples

  # keycloak
  keycloak:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: keycloak
    hostname: keycloak.localhost
    restart: always
    # ports:
    #   - 8080:8080
    environment:
      #   基本設定
      - TZ=Asia/Tokyo
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak.localhost
      # - KC_HOSTNAME_ADMIN=keycloak.localhost
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      #   DB設定
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      #   プロキシ
      - KC_PROXY_HEADERS=xforwarded
    depends_on:
      - postgres
    networks:
      - docker_compose_samples
    command:
      - start-dev
      # - start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"

networks:
  docker_compose_samples:
    external: true
