---
global:
  resolve_timeout: 5m
  smtp_smarthost: mailpit:1025
  smtp_from: Alertmanager<alertmanager@example.com>
  smtp_require_tls: false
  # slack_api_url: 'https://hooks.slack.com/services/***/***/******'
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'default'
    email_configs:
      - to: test@example.com
        require_tls: false
    slack_configs:
      - channel: '#アプリ開発'

# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']
