dist:
  module: github.com/gmofh-kkt/otel-collector
  name: otel-collector
  description: Custom OpenTelemetry Collector for Project KKT
  output_path: ./otelcol
  otelcol_version: v0.131.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.131.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.131.0

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsemfexporter v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter v0.131.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.131.0

connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.131.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.131.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.131.0
