services:
  redis:
    image: redis
    container_name: redis-container
    restart: always
    ports:
      - '6379:6379'
    environment:
      TZ: JST-9
    volumes:
      - ./docker/volumes/redis/data:/data
    command: redis-server --appendonly yes --requirepass foobared

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-container
    restart: always
    ports:
      - '8081:8081'
    environment:
      REDIS_HOSTS: Index0:redis-container:6379:0:foobared,Index1:redis-container:6379:1:foobared
      TZ: JST-9
    depends_on:
      - redis
